### PR TITLE
Persona 5 Royal Guide

### PR DESCRIPTION
**Pull request by ashcorpdev**
Should be a 'good enough' guide for the game - may need some refinement, but I do think that covers the vast majority of what's required for it.

Let me know if you'd like me to clean anything up/reorganize and I'll get it done ASAP.

### CODE REVIEW

**Comment by ashcorpdev** [comment]
> Thank you so much for working on this!
> 
> A couple of remarks:
> 
> * Since you are including info regarding the mod menu being "finished" by the author, I recommend adding a "Game version" field in the top table showing the games info, as shown in the contribute guide.
> * Since you mentioned the generic depth buffer add-on I would include a link to it. I believe it's on BSD discord server, so probably explaining that and including a server invite link + a link that points towards a message or channel where this add-on is might be more clear.
> 
> I do believe however that we should include this info somewhere else. Maybe in the new Reshade guide, we are planning to write soon:tm:

On point #1, that is definitely worth mentioning - I'll add it once I get home from work 🙂

Regarding point #2, I'm using the 'Generic Depth' addon that comes with Reshade, not a third party one. I think you're referring to a third party one for Reshade 6.0?

I can add a link to that either way if it's required for the latest Reshade release.

Thanks for the feedback!

**Comment by originalnicodr** [comment]
> Regarding point 2, I'm using the 'Generic Depth' addon that comes with Reshade, not a third party one. I think you're referring to a third party one for Reshade 6.0?

My bad! Since there were talks about this add-on that I believe adds functionality to the depth buffer options I thought you were referring to that, not the usual Reshade depth buffer tab! Ignore my comment then, and sorry for the confusion.

**Comment by ashcorpdev** [comment]
No worries! Easy mistake to make given the situation :)

**Comment by originalnicodr** [comment]
Made some small edits. If you are fine with them I will merge it then.

**Comment by ashcorpdev** [comment]
> Made some small edits. If you are fine with them I will merge it then.

Looks good to me - happy for you to merge 👍

**Pull request merged**
