### PR TITLE
Added Baldur's Gate 3 Guide

### PR DESCRIPTION
**Pull request by ashcorpdev**
Created a guide for Baldur's Gate 3.

I have included details about the requirement for ReShade v5.9.1, but this can be removed, if necessary (as once ReShade 5.9.2 is out, the Vulkan issue etc will be resolved anyway.

Let me know if there needs to be any more changes and I'll get on them (or you can edit yourselves, of course).

### CODE REVIEW

**Comment by FransBouma** [comment]
Thanks, could you fix the formatting in the docnet.json file, please?

**Comment by ashcorpdev** [comment]
Quick bump just to see if you need any more changes?

**Comment by FransBouma** [comment]
No, sorry, haven't had time to look at it, will do now.

**Comment by FransBouma** [comment]
docnet.json is still a mess, will correct it

**Comment by FransBouma** [comment]
Overlooked a couple of errors in the start table, will correct them

**Comment by ashcorpdev** [comment]
> docnet.json is still a mess, will correct it

So it was - my bad. Sorry for the extra work!

**Comment by FransBouma** [comment]
np, thanks for the guide!

**Pull request merged**
