### PR TITLE
Added a shader catalogue guide and a section about duplicating shaders in another guide

### PR DESCRIPTION
**Pull request by originalnicodr**
I included some html code in the guide for showing images because I didn't want to include more images in the repo (I don't know how many I will add later and I think it can be annoying to have the files around).

Let me know if it's not possible to have the images like that and I will see what I can do.

### CODE REVIEW

**Comment by FransBouma** [comment]
Not sure which images you're referring to, but if images help with the guide, you should add them. I think we have a lot of space left still

**Comment by FransBouma** [comment]
> CinematicDOF: Based on Unreal Engine 4 DOF technology. 

This isn't true btw, no UE4 tech is in CinematicDOF :) Will correct it

**Comment by FransBouma** [comment]
> (Do check if there is a newer version of the shader in the official repo)

The official repo has 3.1, so no need to link to the forum post. 

There are a couple of non-rendering elements in the markdown: `[//]: # (- **bloom**)` for instance. I've removed these. (also: `[//]: # (- **ReflectiveBumpmapping** no lo agrego por que es el viejo)` :D

I've sorted the shaders under 'Fun effects' (Notepad++, select the lines, -> edit -> line operations)

I see the images now. They're *way* too big. Also they're rendered with in-line html. I'll download them and re-add them to the repo after resizing. Please do that yourself next time :P 

As the site has a guide on CinematicDOF, I'll add a link to that. 
Uploaded

**Comment by originalnicodr** [comment]
Sorry about the cinedof UE4 thing, for some reason I thought you based it in some papers or talks by epic, thanks for fixing that.

I forgot to add the cinedof guide from the site until I made the pull request lol, was going to add it today so thanks for that too c:

The forum post for AmbientLight had a modified version with a dither trigger that let you turn it off because of some artifacts it produced, will check it out if the new one has something like that, if not I think pointing out to the forum post is a good idea.

Yeah the markdown comments were there because there were from shaders either old or that I couldn't find where they were stored (probably for the same reason).

I didn't sorted the fun effects because they were kinda sorted because I was planning on adding more subsections to that, but no worries.

I should have figured out we couldn't use html code, sorry. Will add a resized version of the next ones I add.

Thanks a lot for the help frans!

**Pull request merged**
