### PR TITLE
ShaderToggler - HUD - Sekiro: Shadows Die Twice and Yakuza 0

### PR DESCRIPTION
**Pull request by PweSol**
HUD toggle with the Del key for Sekiro: Shadows Die Twice and Yakuza 0

### CODE REVIEW

**Comment by FransBouma** [comment]
> Minigames are not included yet.
Are you planning to add these in the coming days or later, because if it's in the coming days I'll wait till you've pushed these changes and merge then, otherwise I'll merge now and we'll see when these are eventually added (or not :) )

**Comment by PweSol** [comment]
> > Minigames are not included yet.
> 
> Are you planning to add these in the coming days or later, because if it's in the coming days I'll wait till you've pushed these changes and merge then, otherwise I'll merge now and we'll see when these are eventually added (or not :) )

It's a long game and I would have to replay it all over again. So I don't plan to be adding them soon. I'll do a NG+ eventually. But I do have some weird issues with [ReshadeEffectShaderToggler](https://github.com/4lex4nder/ReshadeEffectShaderToggler) in Sekiro with the currently selected shaders, despite them working fine with ShaderToggler. I'll try to fix that if possible.

I'm mainly doing these HUD disablers for the ReshadeEffectShaderToggler addon. So depth-based shaders like RTGI can be easily used by me or others under the HUD or other such elements. Since some games like Sekiro that I am and will be adding here have a native option to disable the HUD otherwise.

Speaking of ReshadeEffectShaderToggler. I do think it would be great to eventually make a guide for your website on it. Even when it's a fork of your original addon.

**Comment by originalnicodr** [comment]
> Speaking of ReshadeEffectShaderToggler. I do think it would be great to one day make a guide for your website on it. Even when it's a fork of your original addon.

Please feel free to write a guide on it! You can follow (this guide)[https://framedsc.com/contribute.htm] to learn how to do so.

**Comment by PweSol** [comment]
> > Speaking of ReshadeEffectShaderToggler. I do think it would be great to one day make a guide for your website on it. Even when it's a fork of your original addon.
> 
> Please feel free to write a guide on it! You can follow (this guide)[https://framedsc.com/contribute.htm] to learn how to do so.

I don't think I am skillful enough for it. But I can try in the future when I get bored.

**Comment by PweSol** [comment]
This is the final revision for the time being. You can merge it after verifying the changes.

**Comment by FransBouma** [comment]
@PweSol 
> Unfortunately, these don't work with ReshadeEffectShaderToggler. For reasons unknown to me, it either kills or prevents shaders from taking effect. Help in this regard would be appreciated.

Please rephrase to "Unfortunately, these don't work with ReshadeEffectShaderToggler, it either kills or prevents shaders from taking effect."

Although you could also remove this sentence, IMHO. A lot of stuff doesn't work with reshadeeffectshadertoggler

**Comment by FransBouma** [comment]
Thanks!

**Comment by PweSol** [comment]
> @PweSol
> 
> > Unfortunately, these don't work with ReshadeEffectShaderToggler. For reasons unknown to me, it either kills or prevents shaders from taking effect. Help in this regard would be appreciated.
> 
> Please rephrase to "Unfortunately, these don't work with ReshadeEffectShaderToggler, it either kills or prevents shaders from taking effect."
> 
> Although you could also remove this sentence, IMHO. A lot of stuff doesn't work with reshadeeffectshadertoggler

The entire description is then redundant anyway, since most HUD togglers made trough ReshadeToggler intervene with menu anyway.

**Pull request merged**
