### PR TITLE
Prince of Persia - The Sands of Time guide

### PR DESCRIPTION
**Pull request by FarmerPepe**

### CODE REVIEW

**Comment by FarmerPepe** [comment]
Done?

**Comment by FransBouma** [comment]
Heh, you forgot to add it to the docnet.json file. Will do that locally :) Also add the header image to the md file

**Comment by FransBouma** [comment]
Fixed, updated and uploaded!

**Comment by FarmerPepe** [comment]
oof, never dealed with docnet.json sorry. I will take this in the future.

**Comment by FransBouma** [comment]
no worries, was easy to fix ;) Cheers!

**Pull request merged**
