### PR TITLE
Update reshadeuwp.md

### PR DESCRIPTION
**Pull request by ItsProbablyAndy**
- Edited the top section to reflect changes to UWP/Game Pass install process and how standard Reshade steps mostly apply now for this platform. 
- Included alert on potential issues with duplicated inputs on Reshade GUI when using on UWP games
- Added alert highlighting additional "advanced section" is largely unnecessary but retained info in case it is needed in future attempts.

### CODE REVIEW

**Comment by originalnicodr** [comment]
Thanks for the contribution Andy!
One thing tho, it seems that you deleted all the slashes and ':' characters from the file :sweat_smile:, mind adding them back?

**Comment by ItsProbablyAndy** [comment]
Yeah I noticed after I submitted the thing that it classified it as completely deleting the original. I've not changed/altered the rest of the text at large so not sure why those charcters have gone missing. I'll go back in and see if editing just the new section fixes it. (Still getting used to using Git at all lol)

**Comment by originalnicodr** [comment]
Added in 1bedd4735536d1e9448fb3b3aa3f6f8552c61bc5

**Comment by originalnicodr** [comment]
Added in 1bedd4735536d1e9448fb3b3aa3f6f8552c61bc5

**Pull request closed without merging**
