### PR TITLE
Updated guide for Abzu, Death Stranding and Shader Repository

### PR DESCRIPTION
**Pull request by rdutta1999**

### CODE REVIEW

**Review by originalnicodr — CHANGES_REQUESTED** [review]
Thank you so much for the PR!

Would you mind adding the following stuff?
- Game version and DRM that you tested the cheat tables on, following [this part of our contributing guide](https://framedsc.com/contribute.htm#game-stores) (both for the Abzu guide and the missing store from the Death Stranding guide).
- Does the game works with UUU? I don't recall if the cheat tables exist because they were made before the existence of UUU or because the game uses a version of UE4 old enough so it isn't supported. Because if it doesn't work maybe we can take the UUU mention, or write that we have to use these cheat tables because UUU doesn't work.
- Would you mind putting the link to the specific shader toggler you made for the game? Even if it's listed in the shader toggler repository.
- Also you mentioned in pvps CE table section that you can "hide the menu using the HUD toggle inside the table". Does it not have a hotkey attached?
- Optional: Maybe clarifying that to pause and take shots you have to pause the game and turn off the hud, that being with pvps table or with the shader toggler. And that if you want to use Skalls table to use the shader toggler with it. What do you think?

Sorry if this is a bit too much 😄, let me know if you need help with anything.

**Comment by rdutta1999** [comment]
Hey, thanks for the comments.

- I tested both Abzu and DeathStranding from Epic Games Store. I have thus added the EGS icon and the version to the Game Version entry in the respective guides.
- For Abzu, I tested with both UUU 3.x and 4.x, but neither worked. I assumed it could be because I was playing on the EGS version, and thus left it as it is. I think it would be better to remove UUU's mention entirely.
- I had thought about it but didn't see any guide that referenced their own ShaderToggler directly. Thus, felt it would be inappropriate to plug it. Have added it now.
- Yeah, PvP's CT mentions that HUD can be toggled. But it didn't work for me, nor did it have any Hotkey attached to it. Since the description was already written, I refrained from editing it much. As for Skall's table, I attached `INSERT` to the freecam toggle, and have uploaded this edited CT to the repo.
- Makes perfect sense. Have added it.

Let me know what you think. Happy to make further edits and improve upon it. Cheers!

**Review by originalnicodr — APPROVED** [review]
So sorry for the delay here!

May I ask to avoid naming the file `Abzû.md` with the special character? Just in case special characters cause trouble in the future.

Once again, thank you so much for working on this!

**Comment by rdutta1999** [comment]
No worries. Have made the changes. Removed the special characters from the markdown and header files. Also, updated the AC Syndicate guide to properly point to the ShaderToggler .htm file (instead of .md).
Let me know what you think.

**Comment by originalnicodr** [comment]
Sorry that it took so long to merge this. Once again, thank you so much for the PR!

**Pull request merged**
