### PR TITLE
Dead Space Game Guide

### PR DESCRIPTION
**Pull request by r3sus**

### CODE REVIEW

**Comment by originalnicodr** [comment]
Made a banner with image you used so it fits the style of the rest of the guides :)

dead space

I am not sure if the showcase section is necesary, and it would be cool to check if Dead Space supports DSR and hotsampling. One thing you can add is that the game certenly lacks Ansel support.

Thanks for the guide!

**Comment by r3sus** [comment]
Thank you kindly! Updated!

**Comment by FransBouma** [comment]
I'll remove the video link and add https://github.com/ghostinthecamera/PhotomodeCheatTables/blob/master/WIP/Dead%20Space/GITC%20-%20Dead%20Space%20WIP.CT as alternative, it's another table with aob and more usable camera (but xyz movement) however no hotkeys.

**Comment by r3sus** [comment]
Thanks. Anything else I can do to guide? I had an idea to add reference to big albums with screenshots, made with this table: [25 photos by Nikolas](https://www.flickr.com/photos/71866538@N04/albums/72157634458703131) / [53 photos by RMA2kay4](https://www.flickr.com/photos/106822250@N03/albums/72157637019260263)

I was also looking for original guide by jim for ds3.
It is referenced at [DET](https://web.archive.org/web/20140527235516/http://www.deadendthrills.com:80/forum/discussion/93/dead-space-3) and [NeoGAF](https://www.neogaf.com/threads/the-neogaf-screenshotters-compendium-thread.546220/page-7#post-86365225).
The [link to guide](http://www.flickr.com/groups/deadendthrills/discuss/72157631765632995/page2) saved once [on Archive.org](https://web.archive.org/web/2017*/http://www.flickr.com/groups/deadendthrills/discuss/72157631765632995/page2), but [not archived](https://web.archive.org/web/20171224231056/http://www.flickr.com/groups/deadendthrills/discuss/72157631765632995/page2/).
Please, advice, if there's any other way to try get this page or someone has it/guide locally. 

As for ds2, table wasn't shared publicly, altho it exists according to the [reply](https://web.archive.org/web/20160830145827/http://deadendthrills.com/forum/discussion/397/dead-space-2) and [screenshots](https://steamcommunity.com/id/neoenigma/screenshots/?appid=47780).

If it's not right place to write about, I might put it in Issues (or Discussions, if enabled).

**Comment by FransBouma** [comment]
We don't have links to albums in teh guides at the moment so let's leave that out of this for now. I'll merge the guide now.

**Comment by FransBouma** [comment]
deployed. Thanks!

**Comment by r3sus** [comment]
Thank you.

**Comment by r3sus** [comment]
> https://github.com/ghostinthecamera/PhotomodeCheatTables/blob/master/WIP/Dead%20Space/GITC%20-%20Dead%20Space%20WIP.CT as alternative, it's another table with aob and more usable camera (but xyz movement) however no hotkeys.

Hi. I've made a look in Ghost's table - and it's amazing! truly free camera! 

Also it has hotkeys.
Num (0 and .) to turn time off/on. Insert and Delete to turn on/off Free Camera, during which Num 1-9 and arrows used for navigation, change FOV: Num +/-. Char is also movable during it.
There is also Aspect Ratio and Timescale.

Hint: 
Hotkeys can by found in code by searching for 'Hotkey'.
In CE, they can be managed by pressing Ctrl+H on entry.

I've updated table a bit to use single key to toggle: Num0 - time, Del - camera, added Ctrl modifier to Arrows.
https://gist.github.com/r3sus/93edc2c58a25841c30b6effcf7936257

It would be cool, if there's way to make hotkeys work only if game window is active.

**Pull request merged**
